spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: password
    url: jdbc:mysql://127.0.0.1:3306
    username: root
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.1.112:8848/

  application:
    name: rm-member

server:
  port: 7000